// Mocks generated by Mockito 5.4.5 from annotations
// in auth_flutter_app/test/unit/data/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:auth_flutter_app/data/datasources/local/secure_storage_service.dart'
    as _i9;
import 'package:auth_flutter_app/data/datasources/remote/auth_api_service.dart'
    as _i6;
import 'package:auth_flutter_app/data/models/auth_response_model.dart' as _i2;
import 'package:auth_flutter_app/data/models/email_verification_models.dart'
    as _i4;
import 'package:auth_flutter_app/data/models/forgot_password_models.dart'
    as _i5;
import 'package:auth_flutter_app/data/models/login_request_model.dart' as _i8;
import 'package:auth_flutter_app/data/models/user_model.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthResponseModel_0 extends _i1.SmartFake
    implements _i2.AuthResponseModel {
  _FakeAuthResponseModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTokenModel_1 extends _i1.SmartFake implements _i2.TokenModel {
  _FakeTokenModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserModel_2 extends _i1.SmartFake implements _i3.UserModel {
  _FakeUserModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmailVerificationResponseModel_3 extends _i1.SmartFake
    implements _i4.EmailVerificationResponseModel {
  _FakeEmailVerificationResponseModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePasswordResetResponseModel_4 extends _i1.SmartFake
    implements _i5.PasswordResetResponseModel {
  _FakePasswordResetResponseModel_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiService extends _i1.Mock implements _i6.AuthApiService {
  MockAuthApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.AuthResponseModel> loginEmail(
          _i8.LoginRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginEmail,
          [request],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #loginEmail,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseModel>);

  @override
  _i7.Future<_i2.AuthResponseModel> registerEmail(
          _i8.RegisterRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerEmail,
          [request],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #registerEmail,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseModel>);

  @override
  _i7.Future<_i2.AuthResponseModel> loginPhone(Map<String, String>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginPhone,
          [request],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #loginPhone,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseModel>);

  @override
  _i7.Future<_i2.AuthResponseModel> registerPhone(
          Map<String, String>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerPhone,
          [request],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #registerPhone,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseModel>);

  @override
  _i7.Future<_i2.AuthResponseModel> verifyOtp(Map<String, String>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [request],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #verifyOtp,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseModel>);

  @override
  _i7.Future<_i2.AuthResponseModel> sendOtp(Map<String, String>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [request],
        ),
        returnValue:
            _i7.Future<_i2.AuthResponseModel>.value(_FakeAuthResponseModel_0(
          this,
          Invocation.method(
            #sendOtp,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.AuthResponseModel>);

  @override
  _i7.Future<_i2.TokenModel> refreshToken(
          _i8.RefreshTokenRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [request],
        ),
        returnValue: _i7.Future<_i2.TokenModel>.value(_FakeTokenModel_1(
          this,
          Invocation.method(
            #refreshToken,
            [request],
          ),
        )),
      ) as _i7.Future<_i2.TokenModel>);

  @override
  _i7.Future<void> revokeToken(Map<String, String>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #revokeToken,
          [request],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> revokeAllTokens() => (super.noSuchMethod(
        Invocation.method(
          #revokeAllTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.UserModel> getUserProfile() => (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [],
        ),
        returnValue: _i7.Future<_i3.UserModel>.value(_FakeUserModel_2(
          this,
          Invocation.method(
            #getUserProfile,
            [],
          ),
        )),
      ) as _i7.Future<_i3.UserModel>);

  @override
  _i7.Future<_i3.UserModel> updateProfile(Map<String, dynamic>? profileData) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profileData],
        ),
        returnValue: _i7.Future<_i3.UserModel>.value(_FakeUserModel_2(
          this,
          Invocation.method(
            #updateProfile,
            [profileData],
          ),
        )),
      ) as _i7.Future<_i3.UserModel>);

  @override
  _i7.Future<_i4.EmailVerificationResponseModel> verifyEmail(
          _i4.VerifyEmailRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyEmail,
          [request],
        ),
        returnValue: _i7.Future<_i4.EmailVerificationResponseModel>.value(
            _FakeEmailVerificationResponseModel_3(
          this,
          Invocation.method(
            #verifyEmail,
            [request],
          ),
        )),
      ) as _i7.Future<_i4.EmailVerificationResponseModel>);

  @override
  _i7.Future<_i4.EmailVerificationResponseModel> resendVerification(
          _i4.ResendVerificationRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resendVerification,
          [request],
        ),
        returnValue: _i7.Future<_i4.EmailVerificationResponseModel>.value(
            _FakeEmailVerificationResponseModel_3(
          this,
          Invocation.method(
            #resendVerification,
            [request],
          ),
        )),
      ) as _i7.Future<_i4.EmailVerificationResponseModel>);

  @override
  _i7.Future<_i5.PasswordResetResponseModel> forgotPassword(
          _i5.ForgotPasswordRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgotPassword,
          [request],
        ),
        returnValue: _i7.Future<_i5.PasswordResetResponseModel>.value(
            _FakePasswordResetResponseModel_4(
          this,
          Invocation.method(
            #forgotPassword,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.PasswordResetResponseModel>);

  @override
  _i7.Future<_i5.PasswordResetResponseModel> validateResetToken(
          _i5.ValidateResetTokenRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateResetToken,
          [request],
        ),
        returnValue: _i7.Future<_i5.PasswordResetResponseModel>.value(
            _FakePasswordResetResponseModel_4(
          this,
          Invocation.method(
            #validateResetToken,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.PasswordResetResponseModel>);

  @override
  _i7.Future<_i5.PasswordResetResponseModel> resetPassword(
          _i5.ResetPasswordRequestModel? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [request],
        ),
        returnValue: _i7.Future<_i5.PasswordResetResponseModel>.value(
            _FakePasswordResetResponseModel_4(
          this,
          Invocation.method(
            #resetPassword,
            [request],
          ),
        )),
      ) as _i7.Future<_i5.PasswordResetResponseModel>);

  @override
  _i7.Future<void> changePassword(Map<String, String>? passwordData) =>
      (super.noSuchMethod(
        Invocation.method(
          #changePassword,
          [passwordData],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> deleteAccount() => (super.noSuchMethod(
        Invocation.method(
          #deleteAccount,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [SecureStorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSecureStorageService extends _i1.Mock
    implements _i9.SecureStorageService {
  MockSecureStorageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<void> storeToken(_i2.TokenModel? token) => (super.noSuchMethod(
        Invocation.method(
          #storeToken,
          [token],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> storeAuthResponse(_i2.AuthResponseModel? authResponse) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeAuthResponse,
          [authResponse],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i2.TokenModel?> getToken() => (super.noSuchMethod(
        Invocation.method(
          #getToken,
          [],
        ),
        returnValue: _i7.Future<_i2.TokenModel?>.value(),
      ) as _i7.Future<_i2.TokenModel?>);

  @override
  _i7.Future<_i2.AuthResponseModel?> getAuthResponse() => (super.noSuchMethod(
        Invocation.method(
          #getAuthResponse,
          [],
        ),
        returnValue: _i7.Future<_i2.AuthResponseModel?>.value(),
      ) as _i7.Future<_i2.AuthResponseModel?>);

  @override
  _i7.Future<String?> getAccessToken() => (super.noSuchMethod(
        Invocation.method(
          #getAccessToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<String?> getRefreshToken() => (super.noSuchMethod(
        Invocation.method(
          #getRefreshToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<bool> hasValidToken() => (super.noSuchMethod(
        Invocation.method(
          #hasValidToken,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<bool> isTokenExpiringSoon() => (super.noSuchMethod(
        Invocation.method(
          #isTokenExpiringSoon,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);

  @override
  _i7.Future<void> clearTokens() => (super.noSuchMethod(
        Invocation.method(
          #clearTokens,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> storeUserPreference(
    String? key,
    String? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #storeUserPreference,
          [
            key,
            value,
          ],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> getUserPreference(String? key) => (super.noSuchMethod(
        Invocation.method(
          #getUserPreference,
          [key],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> storeBiometricEnabled(bool? enabled) => (super.noSuchMethod(
        Invocation.method(
          #storeBiometricEnabled,
          [enabled],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<bool> isBiometricEnabled() => (super.noSuchMethod(
        Invocation.method(
          #isBiometricEnabled,
          [],
        ),
        returnValue: _i7.Future<bool>.value(false),
      ) as _i7.Future<bool>);
}
